#!/bin/sh

local_master_hash="$(git rev-parse master)"
origin_master_hash="$(git rev-parse origin/master)"

if [ "$local_master_hash" = "$origin_master_hash" ]; then
  echo "Local and origin repos match master branch."
  echo "skipping pre-push check..."
  exit 0;
fi
echo "Local and origin repos have different master branches."
echo "proceeding with pre-push hook."

if ! git diff --exit-code --quiet HEAD -- $(git rev-parse --show-toplevel)/_mirror_code/script.gs; then
  # we need everything committed because the test script checks against the working directory, it doesn't pull off the committed file.
  echo "ERROR: Uncommitted changes in _mirror_code/script.gs"
  echo "please commit these changes before pushing."
  exit 3;
fi

echo "comparing local _mirror_code/script.gs to deployed script.gs"
if [ "$(git branch --show-current)" != "master" ]; then
  echo "ERROR: current branch needs to be master for script comparison!"
  echo "cancelling push."
  exit 2;
fi

# Silently check if local script.gs matches deployed script.gs
if $(git rev-parse --show-toplevel)/_mirror_code/test_gs.sh -s; then
	# zero exit status. No differences.
	exit 0;
else
	# non-zero exit status. Local and deployed do not match.
	echo "PUSH ERROR! local ./_mirror_code/script.gs does not match deployed script.gs!"
	echo "Perhaps update the local code to match?"
	echo "  \$(git rev-parse --show-toplevel)/_mirror_code/test_gs.sh -u # update local script.gs"
	echo "Push cancelled."
	exit 1;
fi
